### ISSUE TITLE
Babel 6 support

### ISSUE THREAD

**Issue by kohver** [UXtemple/babel-plugin-react-autoprefix#15]
For reference: [new plugin API](http://babeljs.io/blog/2015/10/29/6.0.0/#plugin-api).

Here is the error:

```
ERROR in ./src/index.js
Module build failed: TypeError: Plugin is not a function
    at exports.default (<project_path>/node_modules/babel-plugin-react-autoprefix/index.js:91:10)
    at Function.memoisePluginContainer (<project_path>/node_modules/babel-core/lib/transformation/file/options/option-manager.js:127:13)
    at Function.normalisePlugin (<project_path>/node_modules/babel-core/lib/transformation/file/options/option-manager.js:161:32)
    at <project_path>/node_modules/babel-core/lib/transformation/file/options/option-manager.js:197:30
    at Array.map (native)
    at Function.normalisePlugins (<project_path>/node_modules/babel-core/lib/transformation/file/options/option-manager.js:173:20)
    at OptionManager.mergeOptions (<project_path>/node_modules/babel-core/lib/transformation/file/options/option-manager.js:271:36)
    at OptionManager.addConfig (<project_path>/node_modules/babel-core/lib/transformation/file/options/option-manager.js:221:10)
    at OptionManager.findConfigs (<project_path>/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:16)
    at OptionManager.init (<project_path>/node_modules/babel-core/lib/transformation/file/options/option-manager.js:412:12)
 @ multi main
```

**Comment by dtothefp** [comment]
any updates on this?? seems like the rest of the commonly used plugins for React development have caught up to Babel 6

**Comment by oguzbilgic** [comment]
+1. Would be really useful

**Comment by quangrau** [comment]
+1 Same problem

**Comment by jmaguirrei** [comment]
+1 Same problem. Any workaround?

**Comment by pke** [comment]
This can be fixed but not using `Plugin` but the plugin is still broken with Babel 6.x in the `isStyle` function

```
$ echo "const component = () => ( <div style={{ display:'flex'}}/> )" | babel --presets react --plugins ./node_modules/babel-plugin-react-autoprefix/index.js
TypeError: unknown: Cannot read property 'name' of undefined
    at isStyle (node_modules\babel-plugin-react-autoprefix\index.js:20:19)
```
